# name: Laravel CI-CD

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     name: Build and Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Changed Repository
#         uses: actions/checkout@v3
#       - name: Setup Enviroment
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: "8.2"
#       - name: Install Packages
#         run: composer install --no-dev

#       - name: autoload
#         run: composer dump-autoload

#       - name: Clear route
#         run: php artisan route:clear

#       - name: Clear Cache
#         run: php artisan cache:clear

#       - name: Clear Config
#         run: php artisan config:clear

#       - name: Configure SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "$SSH_KEY" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           echo "$SSH_PASSPHRASE" > ~/.ssh/passphrase
#           chmod 600 ~/.ssh/passphrase
#         env:
#           SSH_SECRET: ${{ secrets.SSH_KEY }}
#           SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

#       - name: executing remote ssh commands to deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: "65002"
#           password: ${{ secrets.PASSSWORD }}
#           script: "cd /home/u623889396/domains/tobiolanitori.com/public_html/surveylite  && chmod +x deploy.sh"

          # script: |
          #   cd /home/u623889396/domains/tobiolanitori.com/public_html/surveylite && chmod +x deploy.sh
          #   cd /home/u623889396/domains/tobiolanitori.com/public_html/surveylite
          #   ./deploy.sh
name: Survey Lite Backend Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Give checkout permission
        run: chmod -R 777 /home/u623889396/domains/tobiolanitori.com/public_html/surveylite

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Autoload
        run: composer dump-autoload

      - name: Clear route
        run: php artisan route:clear

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Clear Config
        run: php artisan config:clear

      - name: Generate storage link
        run: php artisan storage:link

      - name: Migrate Database
        run: php artisan migrate:fresh --force

      - name: Give permissions
        run:  |
          chown -R www-data.www-data /home/u623889396/domains/tobiolanitori.com/public_html/surveylite/storage
          chown -R www-data.www-data /home/u623889396/domains/tobiolanitori.com/public_html/surveylite/bootstrap/cache
          chmod -R 777 /home/u623889396/domains/tobiolanitori.com/public_html/surveylite/storage
          chmod -R 777 /home/u623889396/domains/tobiolanitori.com/public_html/surveylite/bootstrap/cache
