name: Laravel CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Changed Repository
        uses: actions/checkout@v3
      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install Packages
        run: composer install --no-dev

      - name: autoload
        run: composer dump-autoload

      - name: Clear route
        run: php artisan route:clear

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Clear Config
        run: php artisan config:clear

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_PASSPHRASE" > ~/.ssh/passphrase
          chmod 600 ~/.ssh/passphrase
        env:
          SSH_SECRET: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          port: "65002"
          password: ${{ secrets.PASSSWORD }}
          script: "cd /home/u623889396/domains/tobiolanitori.com/public_html/surveylite && deploy.sh"

          # script: |
          #   cd /home/u623889396/domains/tobiolanitori.com/public_html/surveylite && chmod +x deploy.sh
          #   cd /home/u623889396/domains/tobiolanitori.com/public_html/surveylite
          #   ./deploy.sh
