name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Configure SSH Keyy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: Set Git User Identity
        run: |
          git config --global user.email "tobiolanitori@gmail.com"
          git config --global user.name "Tobi Olanitori"

      - name: Push to Build Branch
        run: |
          git remote set-url origin "git@github.com:${{ github.repository }}"
          git checkout -b build
          git add .
          git commit -m "Build and deploy updates"
          git push origin build
